version: "3.8"

services:
  db:
    image: postgres:16
    container_name: accounts-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  account-service:
    build: .
    container_name: accounts-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accounts
      SPRING_DATASOURCE_USERNAME: account
      SPRING_DATASOURCE_PASSWORD: account
    ports:
      - "8081:8081"
    networks:
      - app-network
    command: >
      sh -c "sleep 10 && java -jar app.jar"
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  db_data: